### ISSUE TITLE
if joint.occurrenceTwo.component.name == 'base_link': AttributeError

### ISSUE THREAD

**Issue by ruk-shan** [syuntoku14/fusion2urdf#51]
Error- 
Failed:
Traceback (most recent call last):
  File "C:/Users/rukshan/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/URDF_Exporter/URDF_Exporter.py", line 59, in run
    joints_dict, msg = Joint.make_joints_dict(root, msg)
  File "C:/Users/rukshan/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/URDF_Exporter\core\Joint.py", line 172, in make_joints_dict
    if joint.occurrenceTwo.component.name == 'base_link':
AttributeError: 'NoneType' object has no attribute 'component'
![image](https://user-images.githubusercontent.com/59415338/125658380-f37fb0c9-22f3-482a-834d-13d76d257c95.png)

**Comment by rohit-kumar-j** [comment]
Your component name is **"base_link (2)"**, while the body name is **"base_link"**. Change the component name to **"base_link"** and the body name can be whatever you want

Close the issue if this solves the problem.

**Comment by chasebrignac** [comment]
What if there is a version number always appended to the body name?

**Comment by chasebrignac** [comment]
@rohit-kumar-j Thank you so much!

**Comment by sof-danny** [comment]
Suppose anyone is still having this error. I found that the problem was that the joints were not well created. To check if your joints are well-designed, follow the steps below:
1. Click on joints in your workspace
2. Right-click on the individual joints 
3. Click on select components. It should highlight the two components that make up the joint. If only one component is highlighted, you need to edit the joints or delete and make a new one. It could be that you selected the wrong components, or you didn't select the base_link first
4. Do this for all the joints
5. Save this version and rerun the fusion2urdf script. It should work now

**Comment by owenchen0408** [comment]
@rohit-kumar-j I am encountering the same isue, 
![image](https://github.com/user-attachments/assets/c317d90b-2372-4958-8008-e188f0af1b45)
I have everything defined and all component have only one body. I also have base link but it still doesn't work. Please help:) thanks!
