### ISSUE TITLE
There is no base_link. Please set base_link and run again.

### ISSUE THREAD

**Issue by VaibhavMall** [syuntoku14/fusion2urdf#64]
I'm trying to export a fusion file to URDF, but it's throwing this error. "There is no base_link. Please set base_link and run again." I'm not able to understand how to troubleshoot this.

**Comment by carpit680** [comment]
Rename the root link of your cad model to base_link. In your case I assume base_plate needs to be renamed.

**Comment by FawaazMoinn** [comment]
I'm too facing a similar problem, and this problem stays always whenever I'm making a urdf, help would be appreciated

![image](https://user-images.githubusercontent.com/69638726/187274203-ed7e68f6-c210-4e31-9b5d-10a83e2f6759.png)

**Comment by FawaazMoinn** [comment]
Im too facing this probelm

Failed:
Traceback (most recent call last):
  File "C:/Users/Admin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/URDF_Exporter/URDF_Exporter.py", line 59, in run
    joints_dict, msg = Joint.make_joints_dict(root, msg)
  File "C:\Users/Admin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/URDF_Exporter\core\Joint.py", line 172, in make_joints_dict
    if joint.occurrenceTwo.component.name == 'base_link':
AttributeError: 'NoneType' object has no attribute 'component'


![image](https://user-images.githubusercontent.com/69638726/187274655-73886985-dd49-489b-ba8f-c6bdcfca822b.png)

**Comment by akashsuthan** [comment]
> Rename the root link of your cad model to base_link. In your case I assume base_plate needs to be renamed.

did you find any way to rectify this even I too have this same issue
