### ISSUE TITLE
Traceback error while making urdf

### ISSUE THREAD

**Issue by FawaazMoinn** [syuntoku14/fusion2urdf#65]
Im facing this error whenever I'm making a urdf, I'm new to urdf making with fusion 360, help would be appreciated

Failed:
Traceback (most recent call last):
  File "C:/Users/Admin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/URDF_Exporter/URDF_Exporter.py", line 59, in run
    joints_dict, msg = Joint.make_joints_dict(root, msg)
  File "C:\Users/Admin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/Scripts/URDF_Exporter\core\Joint.py", line 172, in make_joints_dict
    if joint.occurrenceTwo.component.name == 'base_link':
AttributeError: 'NoneType' object has no attribute 'component'

![image](https://user-images.githubusercontent.com/69638726/187275105-0eba1017-5813-4502-914d-ab2d3dc4fad2.png)

**Comment by mefrankli** [comment]
We have to follow specific design practices to get the fusion to URDF  plugin working,
We should mention at least one component as base_link, setting up the origin and orientation.. as ROS /Gazebo coordinate system is different from the Fusion360's  XYZ, You can refer to [this link](https://rulshi.blogspot.com/2022/10/how-to-create-robot-urdf.html) to get more clarity and easy steps for the same
